// src/frontend/src/components/Chart.jsx
import { useEffect, useRef } from 'react'
import { createChart } from 'lightweight-charts'

function Chart({ data, type = 'line' }) {
  const chartContainerRef = useRef()
  const chartRef = useRef()
  const seriesRef = useRef()

  useEffect(() => {
    if (!chartContainerRef.current) return

    // Create chart
    chartRef.current = createChart(chartContainerRef.current, {
      width: chartContainerRef.current.clientWidth,
      height: 300,
      layout: {
        background: { color: '#ffffff' },
        textColor: '#333',
      },
      grid: {
        vertLines: { color: '#f0f0f0' },
        horzLines: { color: '#f0f0f0' },
      },
      timeScale: {
        borderColor: '#cccccc',
      },
      rightPriceScale: {
        borderColor: '#cccccc',
      },
    })

    // Add series
    if (type === 'line') {
      seriesRef.current = chartRef.current.addLineSeries({
        color: '#3B82F6',
        lineWidth: 2,
      })
    } else if (type === 'candlestick') {
      seriesRef.current = chartRef.current.addCandlestickSeries({
        upColor: '#10B981',
        downColor: '#EF4444',
        borderDownColor: '#EF4444',
        borderUpColor: '#10B981',
        wickDownColor: '#EF4444',
        wickUpColor: '#10B981',
      })
    }

    // Handle resize
    const handleResize = () => {
      if (chartRef.current && chartContainerRef.current) {
        chartRef.current.applyOptions({
          width: chartContainerRef.current.clientWidth,
        })
      }
    }

    window.addEventListener('resize', handleResize)

    return () => {
      window.removeEventListener('resize', handleResize)
      if (chartRef.current) {
        chartRef.current.remove()
      }
    }
  }, [type])

  useEffect(() => {
    if (seriesRef.current && data && data.length > 0) {
      seriesRef.current.setData(data)
    }
  }, [data])

  return (
    <div className="w-full">
      <div ref={chartContainerRef} className="w-full h-[300px]" />
    </div>
  )
}

export default Chart

// src/frontend/src/lib/Chart.svelte
<script>
	import { onMount } from 'svelte';
	import { createChart } from 'lightweight-charts';

	export let data = [];
	export let title = 'Chart';
	export let height = 300;

	let chartContainer;
	let chart;
	let series;

	onMount(() => {
		chart = createChart(chartContainer, {
			width: chartContainer.clientWidth,
			height: height,
			layout: {
				background: { color: '#ffffff' },
				textColor: '#333'
			},
			grid: {
				vertLines: { color: '#f0f0f0' },
				horzLines: { color: '#f0f0f0' }
			},
			timeScale: {
				timeVisible: true,
				secondsVisible: false
			}
		});

		console.log('Chart object:', chart);
		console.log('addLineSeries exists?', typeof chart.addLineSeries);

		series = chart.addLineSeries({
			color: '#3b82f6',
			lineWidth: 2
		});

		if (data.length > 0) {
			series.setData(data);
			chart.timeScale().fitContent();
		}

		const handleResize = () => {
			chart.applyOptions({ width: chartContainer.clientWidth });
		};

		window.addEventListener('resize', handleResize);

		return () => {
			window.removeEventListener('resize', handleResize);
			chart.remove();
		};
	});

	$: if (series && data.length > 0) {
		series.setData(data);
		chart.timeScale().fitContent();
	}
</script>

<div class="chart-wrapper">
	<h3>{title}</h3>
	<div bind:this={chartContainer} class="chart-container"></div>
</div>

<style>
	.chart-wrapper {
		margin: 1rem 0;
	}

	h3 {
		margin: 0 0 0.5rem 0;
		font-size: 1rem;
		color: #666;
	}

	.chart-container {
		width: 100%;
		border-radius: 8px;
		overflow: hidden;
	}
</style>
